AWSTemplateFormatVersion: 2010-09-09
Description: "kakoten web front"
Parameters:
  TagName:
    Type: String
  DefaultRegion:
    Type: String
  Env:
    Type: String
    Description: deploy stage
    AllowedValues:
      - dev
      - stg
      - prod
  S3DeployBucketName:
    Description: "S3 bucket name to deploy"
    Type: "AWS::SSM::Parameter::Value<String>"
    Default: ""
  APIGatewayID:
    Description: "Resource ID of API Gateway"
    Type: "AWS::SSM::Parameter::Value<String>"
    Default: ""
  AcmID:
    Description: "ACM ID"
    Type: "AWS::SSM::Parameter::Value<String>"
    Default: ""
  CustomDomain:
    Description: "Custom domain URL to deploy"
    Type: "AWS::SSM::Parameter::Value<String>"
    Default: ""
Resources:
  #================================================================================
  # S3 Bucket to deploy (store builded source of React)
  #================================================================================
  S3DeployBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref S3DeployBucketName
      OwnershipControls:
        Rules:
          - ObjectOwnership: ObjectWriter
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3DeployBucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - s3:GetObject
            Effect: Allow
            Resource:
              - !Sub arn:aws:s3:::${S3DeployBucketName}/*
            Principal:
              Service: cloudfront.amazonaws.com
            Condition:
              StringEquals:
                AWS:SourceArn: !Sub arn:aws:cloudfront::${AWS::AccountId}:distribution/${CloudFrontDistribution}

  #================================================================================
  # Cloud Front
  #================================================================================
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Comment: !Sub ${TagName}-distribution
        Aliases:
          - !Ref CustomDomain
        ViewerCertificate:
          AcmCertificateArn: !Sub arn:aws:acm:us-east-1:${AWS::AccountId}:certificate/${AcmID}
          MinimumProtocolVersion: "TLSv1.2_2021"
          SslSupportMethod: "sni-only"
        Origins:
          - DomainName: !GetAtt S3DeployBucket.RegionalDomainName
            Id: S3Origin
            OriginAccessControlId: !GetAtt OAC.Id
            S3OriginConfig:
              OriginAccessIdentity: ""
          - DomainName: !Sub ${APIGatewayID}.execute-api.ap-northeast-1.amazonaws.com
            Id: APIGatewayOrigin
            CustomOriginConfig:
              OriginProtocolPolicy: https-only
        Enabled: true
        DefaultRootObject: index.html
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          Compress: true
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6 # CachingOptimized (Recommended for S3)
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
          CachedMethods:
            - GET
            - HEAD
          FunctionAssociations:
            - EventType: viewer-request
              FunctionARN: !GetAtt CloudFrontFunctionIpRestrict.FunctionARN
        CacheBehaviors:
          - PathPattern: "/prod/*"
            TargetOriginId: APIGatewayOrigin
            ViewerProtocolPolicy: https-only
            CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad # disable (Recommended for API Gateway)
            OriginRequestPolicyId: b689b0a8-53d0-40ab-baf2-68738e2966ac # AllViewerExceptHostHeader (Recommended for API Gateway)
            AllowedMethods:
              - GET
              - HEAD
              - OPTIONS
              - PUT
              - PATCH
              - POST
              - DELETE
        PriceClass: PriceClass_200 # 100 or 200 or ALL (no available class_100 in Japan)
        Restrictions:
          GeoRestriction:
            RestrictionType: whitelist
            Locations:
              - JP
  #================================================================================
  # OAC
  #================================================================================
  OAC:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Description: Access Control
        Name: !Sub ${TagName}-oac
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  #================================================================================
  # Global IP whiteList restriction
  #================================================================================
  CloudFrontFunctionIpRestrict:
    Type: AWS::CloudFront::Function
    Properties:
      Name: !Sub ${TagName}-ip-restrict
      FunctionConfig:
        Comment: !Sub ${TagName}-ip-restrict
        Runtime: cloudfront-js-1.0
      AutoPublish: true
      FunctionCode: !Sub |
        function handler(event) {
            var request = event.request;
            var clientIP = event.viewer.ip;

            // IP address to allow access
            var IP_BLACK_LIST = [""];

            var isPermittedIp = !IP_BLACK_LIST.includes(clientIP);

            if (isPermittedIp) {
                // if true(in whitelist), return origin response
                return request;
            } else {
                var errorResponse = {
                    statusCode: 403,
                    statusDescription: 'Forbidden',
                }
                // if false(not in whitelist), return forbidden response
                return errorResponse;
            }
        }
